service: blog

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: dev
  region: us-east-1

functions:
  new:
    handler: PostController.new
    events:
      - http:
          path: posts
          method: post
          cors: true
  view:
    handler: PostController.view
    events:
      - http:
          path: posts/{id}
          method: get
          cors: true
  index:
    handler: PostController.index
    events:
     - http:
         path: posts
         method: get
         cors: true
  update:
    handler: PostController.update
    events:
     - http:
         path: posts/{id}
         method: put
         cors: true
  delete:
    handler: PostController.delete
    events:
     - http:
         path: posts/{id}
         method: delete
         cors: true

plugins:
- serverless-offline