service: express-app

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128

functions: # add 4 functions for CRUD
  new:
    handler: PostController.new # point to exported create function in handler.js
    events:
      - http:
          path: posts # path will be domain.name.com/dev/notes
          method: post
          cors: true
  view:
    handler: PostController.view
    events:
      - http:
          path: posts/{id} # path will be domain.name.com/dev/notes/1
          method: get
          cors: true
  index:
    handler: PostController.index # path will be domain.name.com/dev/notes
    events:
     - http:
         path: posts
         method: get
         cors: true
  update:
    handler: PostController.update # path will be domain.name.com/dev/notes/1
    events:
     - http:
         path: posts/{id}
         method: put
         cors: true
  delete:
    handler: PostController.delete
    events:
     - http:
         path: posts/{id} # path will be domain.name.com/dev/notes/1
         method: delete
         cors: true

plugins:
  - serverless-offline
